"""
Django settings for Personal_Portfolio project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import hashlib
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env. The path is passed
# explicitly so the file is found no matter which directory `manage.py` (or a
# systemd unit) is invoked from; letting python-dotenv search from the current
# working directory made configuration depend on where the command was run.
#
# Note this does NOT override variables already present in the environment —
# an exported GITHUB_USERNAME= would win over the file.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# A real SECRET_KEY must be provided in production (e.g. via .env).
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-n0!=w*g*36-c=f(*^0a7gsaur031ys8-5ngn#6hpus&8^1u4ac'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG is False. "
            "Set it in your .env file."
        )

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF protection for domains behind proxy (Cloudflare)
CSRF_TRUSTED_ORIGINS = [
    'https://armin2080.de',
    'https://www.armin2080.de'
]

# Canonical site origin, used for canonical/Open Graph URLs and robots.txt.
SITE_URL = os.environ.get('SITE_URL', 'https://armin2080.de').rstrip('/')

# Help Django understand it's behind a proxy (Cloudflare)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django_recaptcha',
    'portfolio_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must come after AuthenticationMiddleware so it can skip staff requests.
    'portfolio_app.middleware.PageViewMiddleware',
]

ROOT_URLCONF = 'Personal_Portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portfolio_app.context_processors.profile_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Personal_Portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Local time for this German portfolio: also makes the daily statistics bucket
# by local calendar day instead of shifting over at 01:00/02:00 local time.
TIME_ZONE = os.environ.get('TIME_ZONE', 'Europe/Berlin')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))

# If you're using a custom directory for static files, ensure it's correctly set up
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Adjust based on where you store your static files.
]

# Content-hashed filenames for static files.
#
# Static files are served with a long cache lifetime, so a browser or proxy can
# hold a copy after the HTML has moved on. That combination broke the layout
# badly once: a cached stylesheet still used the old theme token names while the
# markup used the new ones, so the nav lost its background and images rendered
# unstyled for anyone with the old copy.
#
# With a manifest, the filename changes whenever the content changes, so a stale
# copy is simply never requested again. CompressedManifestStaticFilesStorage also
# pre-compresses for WhiteNoise.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'Personal_Portfolio.storage.LenientManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cache for rate limiting (file-based works with a single worker)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.environ.get('CACHE_LOCATION', '/tmp/django_cache'),
    }
}

# Behind Cloudflare REMOTE_ADDR is the proxy's address, so django-ratelimit would
# put every visitor in one shared bucket (3 blocked messages per hour site-wide).
# Resolve the real client IP instead — see portfolio_app/utils.client_ip.
RATELIMIT_IP_META_KEY = 'portfolio_app.utils.client_ip'

# Whether to trust CF-Connecting-IP / X-Forwarded-For when identifying a client.
# Only enable this when the app is reachable exclusively through the proxy:
# otherwise a client can spoof the header to dodge the contact form rate limit.
TRUST_PROXY_HEADERS = os.environ.get('TRUST_PROXY_HEADERS', 'True') == 'True'


# Visitor statistics (private admin dashboard)
# Records anonymous page views in this database only: no cookies, no third
# parties, no raw IP addresses. See portfolio_app/analytics.py and the README.
ANALYTICS_ENABLED = os.environ.get('ANALYTICS_ENABLED', 'True') == 'True'

# Secret used to derive the daily visitor pseudonym. Keep it private — anyone
# who knows it can brute-force the (small) space of IP addresses.
ANALYTICS_SALT = os.environ.get('ANALYTICS_SALT', '')
if not ANALYTICS_SALT:
    # Derive a distinct secret so the raw SECRET_KEY is never reused directly.
    ANALYTICS_SALT = hashlib.sha256(f"analytics:{SECRET_KEY}".encode('utf-8')).hexdigest()

# Page views older than this are removed by `manage.py purge_pageviews`
# (installed as a daily systemd timer — see SYSTEMD_DEPLOY.md).
ANALYTICS_RETENTION_DAYS = int(os.environ.get('ANALYTICS_RETENTION_DAYS', '180'))


# GitHub project sync (see portfolio_app/github_sync.py)
# Public repositories are imported as projects by `manage.py sync_github_projects`,
# which a systemd timer runs daily. Nothing is ever deleted, and edits made in the
# admin to a project's name, description, link, photo, category or skills are not
# overwritten.
GITHUB_USERNAME = os.environ.get('GITHUB_USERNAME', '')

# Optional. Without a token the API allows 60 requests per hour, which is ample
# for one sync a day; a token is only needed to raise that limit or to reach
# private repositories.
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')

# reCAPTCHA (Google reCAPTCHA v3 – invisible)
# Empty values and the .env.example placeholders must count as "not configured".
# Defining an empty key would otherwise make every submission fail validation.
_recaptcha_public_key = os.environ.get('RECAPTCHA_PUBLIC_KEY', '').strip()
_recaptcha_private_key = os.environ.get('RECAPTCHA_PRIVATE_KEY', '').strip()
_recaptcha_configured = all(
    key and not key.startswith('your-recaptcha')
    for key in (_recaptcha_public_key, _recaptcha_private_key)
)

if _recaptcha_configured:
    RECAPTCHA_PUBLIC_KEY = _recaptcha_public_key
    RECAPTCHA_PRIVATE_KEY = _recaptcha_private_key
elif not DEBUG:
    raise ImproperlyConfigured(
        "RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY are required when DEBUG "
        "is False, otherwise the contact form rejects every submission."
    )
else:
    # Development: fall back to the test keys that Google and django-recaptcha
    # publish for exactly this purpose. They are read from the library instead
    # of being hardcoded here, which keeps key-shaped strings out of the
    # repository (secret scanners flag any hardcoded key) and stays correct if
    # upstream ever rotates them. The captcha field is skipped while DEBUG is on
    # (see portfolio_app/forms.py); django-recaptcha still needs these defined,
    # and its "test keys in use" check silenced.
    from django_recaptcha.constants import TEST_PRIVATE_KEY, TEST_PUBLIC_KEY

    RECAPTCHA_PUBLIC_KEY = TEST_PUBLIC_KEY
    RECAPTCHA_PRIVATE_KEY = TEST_PRIVATE_KEY
    SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']


# 'console' prints emails to terminal (safe for dev), 'smtp' sends real emails.
# Default to SMTP in production so contact-form messages are actually delivered.
_default_email_backend = 'console' if DEBUG else 'smtp'
if os.environ.get('EMAIL_BACKEND', _default_email_backend) == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# `manage.py prune_media` deletes media files nothing references. Files modified
# within this many hours are left alone, because Django writes the file just
# before the database row that points at it: a new upload momentarily looks
# unreferenced, and an automated run must not delete one.
MEDIA_PRUNE_MIN_AGE_HOURS = int(os.environ.get('MEDIA_PRUNE_MIN_AGE_HOURS', '24'))


# Security settings for production (behind Cloudflare / a TLS-terminating proxy)
if not DEBUG:
    # Redirect all plain-HTTP requests to HTTPS.
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
