# Generated by Django 5.2 on 2025-05-01 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default=datetime.datetime(2025, 5, 1, 15, 59, 33, 514022, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
