# Generated by Django 5.2 on 2025-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_education_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Soft', 'Soft')], default='Technical', max_length=100),
        ),
    ]
