# Generated by Django 6.0.2 on 2026-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_remove_certificate_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Armin', max_length=100)),
                ('title', models.CharField(default='Data Scientist & Developer', max_length=200)),
                ('bio', models.TextField(default='I transform complex data into actionable insights and build intelligent solutions.')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('available_for_hire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
