# Generated by Django 6.0.2 on 2026-06-14 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_categories_from_existing_projects(apps, schema_editor):
    Category = apps.get_model('portfolio_app', 'Category')
    Project = apps.get_model('portfolio_app', 'Project')
    for project in Project.objects.all():
        if project.category and not Category.objects.filter(name=project.category).exists():
            Category.objects.create(name=project.category)


def map_project_categories(apps, schema_editor):
    """Nullify category values before the FK change, then link to Category objects."""
    Category = apps.get_model('portfolio_app', 'Category')
    Project = apps.get_model('portfolio_app', 'Project')
    for project in Project.objects.all():
        if project.category:
            cat, _ = Category.objects.get_or_create(name=project.category)
            project.category = cat.pk
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_profile_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            create_categories_from_existing_projects,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Detailed summary shown on the resume page'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_de',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_en',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='preview',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='One-line preview shown on project cards', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Full project details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio_app.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(help_text='Skill proficiency from 1 to 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Soft', 'Soft')], default='Technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(
            map_project_categories,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio_app.category'),
        ),
    ]
