# Generated by Django 6.0.2 on 2026-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_category_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='e.g. Bachelor of Science in Computer Science', max_length=200),
        ),
    ]
