# Generated by Django 6.1.1 on 2026-09-28 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, help_text='ISO country code from Cloudflare (blank when unknown)', max_length=2)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], max_length=10)),
                ('browser', models.CharField(blank=True, max_length=30)),
                ('os', models.CharField(blank=True, max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=100)),
                ('visitor_hash', models.CharField(blank=True, help_text='Rotates daily; cannot be used to track a visitor over time', max_length=16)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page view',
                'verbose_name_plural': 'Page views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='portfolio_a_viewed__55738b_idx'), models.Index(fields=['is_bot', '-viewed_at'], name='portfolio_a_is_bot_f96e5a_idx')],
            },
        ),
    ]
