# Generated by Django 6.1.1 on 2026-09-28 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0020_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one theme can be active; activating this one deactivates the others.')),
                ('light_primary', models.CharField(default='#1D3557', help_text='Navigation, footer, headings and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Primary')),
                ('light_secondary', models.CharField(default='#457B9D', help_text='Links and secondary actions', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Secondary')),
                ('light_accent', models.CharField(default='#A8DADC', help_text='Soft highlights, badges and subtle section backgrounds', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Accent')),
                ('light_emphasis', models.CharField(default='#E63946', help_text='Strong accents and calls to action', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Emphasis')),
                ('light_page', models.CharField(default='#F1FAEE', help_text='The overall page background', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Page background')),
                ('light_surface', models.CharField(default='#FFFFFF', help_text='Cards and panels', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Surface')),
                ('light_inverse', models.CharField(default='#F1FAEE', help_text='Text drawn on top of Primary', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Inverse text')),
                ('light_ink', models.CharField(default='#374151', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Body text')),
                ('light_muted', models.CharField(default='#6B7280', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Muted text')),
                ('light_border', models.CharField(default='#D1D5DB', help_text='Dividers and input borders', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Border')),
                ('dark_primary', models.CharField(default='#0F3460', help_text='Navigation, footer, headings and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Primary')),
                ('dark_secondary', models.CharField(default='#457B9D', help_text='Links and secondary actions', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Secondary')),
                ('dark_accent', models.CharField(default='#A8DADC', help_text='Soft highlights, badges and subtle section backgrounds', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Accent')),
                ('dark_emphasis', models.CharField(default='#E63946', help_text='Strong accents and calls to action', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Emphasis')),
                ('dark_page', models.CharField(default='#1A1A2E', help_text='The overall page background', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Page background')),
                ('dark_surface', models.CharField(default='#16213E', help_text='Cards and panels', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Surface')),
                ('dark_inverse', models.CharField(default='#F1FAEE', help_text='Text drawn on top of Primary', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Inverse text')),
                ('dark_ink', models.CharField(default='#CBD5E1', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Body text')),
                ('dark_muted', models.CharField(default='#94A3B8', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Muted text')),
                ('dark_border', models.CharField(default='#334155', help_text='Dividers and input borders', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Border')),
                ('font_heading', models.CharField(choices=[('inter', 'Inter — clean sans-serif'), ('source-serif', 'Source Serif 4 — serif (editorial)'), ('jetbrains-mono', 'JetBrains Mono — monospace'), ('system', 'System default')], default='inter', help_text='Used for headings and the site name.', max_length=20)),
                ('font_body', models.CharField(choices=[('inter', 'Inter — clean sans-serif'), ('source-serif', 'Source Serif 4 — serif (editorial)'), ('jetbrains-mono', 'JetBrains Mono — monospace'), ('system', 'System default')], default='inter', help_text='Used for body copy and interface text.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
