# Generated by Django 6.1.1 on 2026-09-28 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0021_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='dark_heading',
            field=models.CharField(default='#E2E8F0', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Headings'),
        ),
        migrations.AddField(
            model_name='theme',
            name='light_heading',
            field=models.CharField(default='#1D3557', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Headings'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_border',
            field=models.CharField(default='#334155', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_ink',
            field=models.CharField(default='#CBD5E1', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_muted',
            field=models.CharField(default='#94A3B8', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Muted text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_primary',
            field=models.CharField(default='#0F3460', help_text='Navigation, footer and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_border',
            field=models.CharField(default='#D1D5DB', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_ink',
            field=models.CharField(default='#374151', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_muted',
            field=models.CharField(default='#6B7280', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Muted text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_primary',
            field=models.CharField(default='#1D3557', help_text='Navigation, footer and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as a 6-digit hex value, for example #1D3557.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Primary'),
        ),
    ]
