# Generated by Django 6.1.1 on 2026-09-28 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0022_theme_dark_heading_theme_light_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='dark_accent',
            field=models.CharField(default='#A8DADC', help_text='Soft highlights, badges and subtle section backgrounds', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Accent'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_border',
            field=models.CharField(default='#334155', help_text='Dividers and input borders', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_emphasis',
            field=models.CharField(default='#E63946', help_text='Strong accents and calls to action', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Emphasis'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_heading',
            field=models.CharField(default='#E2E8F0', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Headings'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_ink',
            field=models.CharField(default='#CBD5E1', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_inverse',
            field=models.CharField(default='#F1FAEE', help_text='Text drawn on top of Primary', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Inverse text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_muted',
            field=models.CharField(default='#94A3B8', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Muted text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_page',
            field=models.CharField(default='#1A1A2E', help_text='The overall page background', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Page background'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_primary',
            field=models.CharField(default='#0F3460', help_text='Navigation, footer and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_secondary',
            field=models.CharField(default='#457B9D', help_text='Links and secondary actions', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_surface',
            field=models.CharField(default='#16213E', help_text='Cards and panels', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_accent',
            field=models.CharField(default='#A8DADC', help_text='Soft highlights, badges and subtle section backgrounds', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Accent'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_border',
            field=models.CharField(default='#D1D5DB', help_text='Dividers and input borders', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_emphasis',
            field=models.CharField(default='#E63946', help_text='Strong accents and calls to action', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Emphasis'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_heading',
            field=models.CharField(default='#1D3557', help_text='Headings and brand-coloured emphasis text', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Headings'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_ink',
            field=models.CharField(default='#374151', help_text='Main body copy', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_inverse',
            field=models.CharField(default='#F1FAEE', help_text='Text drawn on top of Primary', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Inverse text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_muted',
            field=models.CharField(default='#6B7280', help_text='Secondary text, captions and metadata', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Muted text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_page',
            field=models.CharField(default='#F1FAEE', help_text='The overall page background', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Page background'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_primary',
            field=models.CharField(default='#1D3557', help_text='Navigation, footer and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_secondary',
            field=models.CharField(default='#457B9D', help_text='Links and secondary actions', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_surface',
            field=models.CharField(default='#FFFFFF', help_text='Cards and panels', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Surface'),
        ),
    ]
