# Generated by Django 6.1.1 on 2026-09-28 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0023_alter_theme_dark_accent_alter_theme_dark_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='dark_primary',
            field=models.CharField(default='#2B3641', help_text='Navigation, footer and primary buttons', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #1D3557 (or the shorthand #abc). Letters A-F and digits 0-9 only.', regex='^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Primary'),
        ),
    ]
