# Generated by Django 6.1.1 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0024_alter_theme_dark_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_full_name',
            field=models.CharField(blank=True, help_text='owner/repo on GitHub, for reference.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.BigIntegerField(blank=True, help_text="GitHub's numeric repository id; how the sync recognises this project.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this project was last seen by the sync.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Untick to hide this project from the site. The GitHub sync never changes this, so hidden projects stay hidden. Note: deleting a GitHub project does not remove it permanently — the next sync will import it again. Untick this instead.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Shown on the project card. Filled in from GitHub on first import; if the repository has no description this is left blank.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Cards show a placeholder until a screenshot is uploaded.', null=True, upload_to='projects/'),
        ),
    ]
