# Generated by Django 6.1.1 on 2026-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0025_project_github_full_name_project_github_repo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_skills',
            field=models.BooleanField(default=True, help_text='Keep the skill tags above in step with what is actually in the repository. The sync adds and removes tags to match, so a tag you remove by hand comes back on the next run. Untick this on a project whose tags you want to manage yourself.'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_pushed_at',
            field=models.CharField(blank=True, help_text="GitHub's pushed_at as last seen. Reading a repository's contents costs API requests, so an unchanged repository is skipped.", max_length=40),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Untick to hide this skill from the site. The GitHub sync creates a newly detected skill unticked, so nothing appears publicly until you have reviewed it and written a description.'),
        ),
        migrations.CreateModel(
            name='SkillSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('path', 'File or folder in the repository'), ('dependency', 'Package in a dependency file'), ('language', "GitHub's main language")], default='path', help_text='What to look at in the repository.', max_length=16)),
                ('pattern', models.CharField(help_text="File rules use a glob, matched against every path and against each path segment: <code>manage.py</code>, <code>*.ipynb</code>, <code>.github/workflows/*</code>. Package rules match a name in requirements.txt, pyproject.toml, Pipfile or package.json — <code>scikit-learn</code> also finds <code>scikit-learn[extra]</code> and <code>scikit-learn-tools</code>, but <code>django</code> does not match <code>djangorestframework</code>. Language rules compare GitHub's reported language.", max_length=100)),
                ('skill_name', models.CharField(help_text='The skill to attach, matched by name. Created (hidden) if no skill has this name yet.', max_length=100)),
                ('note', models.CharField(blank=True, help_text='Optional note for your own reference.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop using this rule without deleting it.')),
            ],
            options={
                'ordering': ['kind', 'pattern', 'skill_name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'pattern', 'skill_name'), name='unique_skill_signal')],
            },
        ),
    ]
