# Generated by Django 6.1.1 on 2026-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0031_seed_statistics_and_llm_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsignal',
            name='pattern',
            field=models.CharField(help_text="File rules use a glob, matched against every path and against each path segment: <code>manage.py</code>, <code>*.ipynb</code>, <code>.github/workflows/*</code>. Package rules match the start of a name in requirements.txt, pyproject.toml, Pipfile or package.json, so <code>psycopg2</code> finds <code>psycopg2-binary</code> and <code>django</code> finds <code>djangorestframework</code>. Keep a package rule specific: a short pattern over-matches. Language rules compare GitHub's reported language.", max_length=100),
        ),
    ]
