# Generated by Django 6.1.1 on 2026-10-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0032_alter_skillsignal_pattern_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'start_date', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers come first on the skills page. Leave at 0 to order by how long you have used the skill instead.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Main skills only. Shown at the top of the card; a placeholder graphic is used until you upload one.', null=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a main skill, which gets its own card. Set a parent to make this a sub-skill listed underneath it. A sub-skill cannot itself have sub-skills.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='portfolio_app.skill'),
        ),
        migrations.AddField(
            model_name='skillsignal',
            name='parent_skill_name',
            field=models.CharField(blank=True, help_text='Only used when this rule has to create the skill. Names the main skill the new sub-skill belongs under, so detection does not drop it at the top level. Leave blank for a main skill.', max_length=100),
        ),
        migrations.AlterField(
            model_name='skillsignal',
            name='skill_name',
            field=models.CharField(help_text='The skill to attach, matched by name. Created (hidden) if no skill has this name yet. Point this at a sub-skill (pandas, PyMC) to keep the detail off the project cards, which roll up to the main skill.', max_length=100),
        ),
    ]
